//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diziler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diziler()
        {
            this.DiziDetay = new HashSet<DiziDetay>();
            this.KullaniciDiziDetay = new HashSet<KullaniciDiziDetay>();
        }
    
        public int DiziId { get; set; }
        public string DiziAdi { get; set; }
        public Nullable<int> YonetmenId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> BolumSayisi { get; set; }
        public Nullable<int> SezonSayisi { get; set; }
        public string Ulkesi { get; set; }
        public string DiziResim { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string DiziOdul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiziDetay> DiziDetay { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Yonetmenler Yonetmenler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciDiziDetay> KullaniciDiziDetay { get; set; }
    }
}
