//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiziDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiziDetay()
        {
            this.DiziOyuncular = new HashSet<DiziOyuncular>();
        }
    
        public int DiziDetayId { get; set; }
        public Nullable<int> DiziId { get; set; }
        public string DiziBolumAdi { get; set; }
        public string BolumIcerik { get; set; }
        public Nullable<System.TimeSpan> BolumSuresi { get; set; }
        public Nullable<System.DateTime> YayinlanmaTarihi { get; set; }
        public string SezonAdi { get; set; }
        public Nullable<int> YasSiniri { get; set; }
        public string DiziVideo { get; set; }
    
        public virtual Diziler Diziler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiziOyuncular> DiziOyuncular { get; set; }
    }
}
