//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmler()
        {
            this.FilmOyuncular = new HashSet<FilmOyuncular>();
            this.KullaniciFilmDetay = new HashSet<KullaniciFilmDetay>();
        }
    
        public int FilmId { get; set; }
        public string FilmAdi { get; set; }
        public Nullable<System.DateTime> VizyonTarihi { get; set; }
        public Nullable<int> FilmSuresi { get; set; }
        public string Konusu { get; set; }
        public string FilmOdul { get; set; }
        public Nullable<int> YasSiniri { get; set; }
        public string Ulkesi { get; set; }
        public string FilmResim { get; set; }
        public string Video { get; set; }
        public Nullable<decimal> FragmanSuresi { get; set; }
        public string FragmanVideo { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> YonetmenId { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Yonetmenler Yonetmenler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmOyuncular> FilmOyuncular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciFilmDetay> KullaniciFilmDetay { get; set; }
    }
}
