//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmProjesiEntities : DbContext
    {
        public FilmProjesiEntities()
            : base("name=FilmProjesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiziDetay> DiziDetay { get; set; }
        public virtual DbSet<Diziler> Diziler { get; set; }
        public virtual DbSet<DiziOyuncular> DiziOyuncular { get; set; }
        public virtual DbSet<Filmler> Filmler { get; set; }
        public virtual DbSet<FilmOyuncular> FilmOyuncular { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<KullaniciDiziDetay> KullaniciDiziDetay { get; set; }
        public virtual DbSet<KullaniciFilmDetay> KullaniciFilmDetay { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Oyuncular> Oyuncular { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Yonetmenler> Yonetmenler { get; set; }
    }
}
