//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.BenimServisim {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanicilar", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Kullanicilar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.KullaniciDiziDetay[] KullaniciDiziDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.KullaniciFilmDetay[] KullaniciFilmDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciSoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Roller RollerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCKNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.KullaniciDiziDetay[] KullaniciDiziDetay {
            get {
                return this.KullaniciDiziDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciDiziDetayField, value) != true)) {
                    this.KullaniciDiziDetayField = value;
                    this.RaisePropertyChanged("KullaniciDiziDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.KullaniciFilmDetay[] KullaniciFilmDetay {
            get {
                return this.KullaniciFilmDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciFilmDetayField, value) != true)) {
                    this.KullaniciFilmDetayField = value;
                    this.RaisePropertyChanged("KullaniciFilmDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciMail {
            get {
                return this.KullaniciMailField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciMailField, value) != true)) {
                    this.KullaniciMailField = value;
                    this.RaisePropertyChanged("KullaniciMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciSoyadi {
            get {
                return this.KullaniciSoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciSoyadiField, value) != true)) {
                    this.KullaniciSoyadiField = value;
                    this.RaisePropertyChanged("KullaniciSoyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Roller Roller {
            get {
                return this.RollerField;
            }
            set {
                if ((object.ReferenceEquals(this.RollerField, value) != true)) {
                    this.RollerField = value;
                    this.RaisePropertyChanged("Roller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCKN {
            get {
                return this.TCKNField;
            }
            set {
                if ((object.ReferenceEquals(this.TCKNField, value) != true)) {
                    this.TCKNField = value;
                    this.RaisePropertyChanged("TCKN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isBanned {
            get {
                return this.isBannedField;
            }
            set {
                if ((this.isBannedField.Equals(value) != true)) {
                    this.isBannedField = value;
                    this.RaisePropertyChanged("isBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                if ((this.isDeletedField.Equals(value) != true)) {
                    this.isDeletedField = value;
                    this.RaisePropertyChanged("isDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roller", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Roller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Kullanicilar[] KullanicilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Kullanicilar[] Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolAdi {
            get {
                return this.RolAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.RolAdiField, value) != true)) {
                    this.RolAdiField = value;
                    this.RaisePropertyChanged("RolAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KullaniciDiziDetay", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class KullaniciDiziDetay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiziIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Diziler DizilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IzlenmeTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciDiziDetayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Kullanicilar KullanicilarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiziId {
            get {
                return this.DiziIdField;
            }
            set {
                if ((this.DiziIdField.Equals(value) != true)) {
                    this.DiziIdField = value;
                    this.RaisePropertyChanged("DiziId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Diziler Diziler {
            get {
                return this.DizilerField;
            }
            set {
                if ((object.ReferenceEquals(this.DizilerField, value) != true)) {
                    this.DizilerField = value;
                    this.RaisePropertyChanged("Diziler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IzlenmeTarihi {
            get {
                return this.IzlenmeTarihiField;
            }
            set {
                if ((this.IzlenmeTarihiField.Equals(value) != true)) {
                    this.IzlenmeTarihiField = value;
                    this.RaisePropertyChanged("IzlenmeTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciDiziDetayId {
            get {
                return this.KullaniciDiziDetayIdField;
            }
            set {
                if ((this.KullaniciDiziDetayIdField.Equals(value) != true)) {
                    this.KullaniciDiziDetayIdField = value;
                    this.RaisePropertyChanged("KullaniciDiziDetayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KullaniciFilmDetay", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class KullaniciFilmDetay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Filmler FilmlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IzlenmeTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciFilmDetayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Kullanicilar KullanicilarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Filmler Filmler {
            get {
                return this.FilmlerField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmlerField, value) != true)) {
                    this.FilmlerField = value;
                    this.RaisePropertyChanged("Filmler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IzlenmeTarihi {
            get {
                return this.IzlenmeTarihiField;
            }
            set {
                if ((this.IzlenmeTarihiField.Equals(value) != true)) {
                    this.IzlenmeTarihiField = value;
                    this.RaisePropertyChanged("IzlenmeTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciFilmDetayId {
            get {
                return this.KullaniciFilmDetayIdField;
            }
            set {
                if ((this.KullaniciFilmDetayIdField.Equals(value) != true)) {
                    this.KullaniciFilmDetayIdField = value;
                    this.RaisePropertyChanged("KullaniciFilmDetayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Kullanicilar Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Diziler", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Diziler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BolumSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiziAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.DiziDetay[] DiziDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiziIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiziOdulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiziResimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KategoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Kategoriler KategorilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.KullaniciDiziDetay[] KullaniciDiziDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SezonSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlkesiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YonetmenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Yonetmenler YonetmenlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BolumSayisi {
            get {
                return this.BolumSayisiField;
            }
            set {
                if ((this.BolumSayisiField.Equals(value) != true)) {
                    this.BolumSayisiField = value;
                    this.RaisePropertyChanged("BolumSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiziAdi {
            get {
                return this.DiziAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziAdiField, value) != true)) {
                    this.DiziAdiField = value;
                    this.RaisePropertyChanged("DiziAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.DiziDetay[] DiziDetay {
            get {
                return this.DiziDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziDetayField, value) != true)) {
                    this.DiziDetayField = value;
                    this.RaisePropertyChanged("DiziDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiziId {
            get {
                return this.DiziIdField;
            }
            set {
                if ((this.DiziIdField.Equals(value) != true)) {
                    this.DiziIdField = value;
                    this.RaisePropertyChanged("DiziId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiziOdul {
            get {
                return this.DiziOdulField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziOdulField, value) != true)) {
                    this.DiziOdulField = value;
                    this.RaisePropertyChanged("DiziOdul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiziResim {
            get {
                return this.DiziResimField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziResimField, value) != true)) {
                    this.DiziResimField = value;
                    this.RaisePropertyChanged("DiziResim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KategoriId {
            get {
                return this.KategoriIdField;
            }
            set {
                if ((this.KategoriIdField.Equals(value) != true)) {
                    this.KategoriIdField = value;
                    this.RaisePropertyChanged("KategoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Kategoriler Kategoriler {
            get {
                return this.KategorilerField;
            }
            set {
                if ((object.ReferenceEquals(this.KategorilerField, value) != true)) {
                    this.KategorilerField = value;
                    this.RaisePropertyChanged("Kategoriler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.KullaniciDiziDetay[] KullaniciDiziDetay {
            get {
                return this.KullaniciDiziDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciDiziDetayField, value) != true)) {
                    this.KullaniciDiziDetayField = value;
                    this.RaisePropertyChanged("KullaniciDiziDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SezonSayisi {
            get {
                return this.SezonSayisiField;
            }
            set {
                if ((this.SezonSayisiField.Equals(value) != true)) {
                    this.SezonSayisiField = value;
                    this.RaisePropertyChanged("SezonSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulkesi {
            get {
                return this.UlkesiField;
            }
            set {
                if ((object.ReferenceEquals(this.UlkesiField, value) != true)) {
                    this.UlkesiField = value;
                    this.RaisePropertyChanged("Ulkesi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YonetmenId {
            get {
                return this.YonetmenIdField;
            }
            set {
                if ((this.YonetmenIdField.Equals(value) != true)) {
                    this.YonetmenIdField = value;
                    this.RaisePropertyChanged("YonetmenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Yonetmenler Yonetmenler {
            get {
                return this.YonetmenlerField;
            }
            set {
                if ((object.ReferenceEquals(this.YonetmenlerField, value) != true)) {
                    this.YonetmenlerField = value;
                    this.RaisePropertyChanged("Yonetmenler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                if ((this.isDeletedField.Equals(value) != true)) {
                    this.isDeletedField = value;
                    this.RaisePropertyChanged("isDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategoriler", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Kategoriler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Diziler[] DizilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Filmler[] FilmlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KategoriAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KategoriIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Diziler[] Diziler {
            get {
                return this.DizilerField;
            }
            set {
                if ((object.ReferenceEquals(this.DizilerField, value) != true)) {
                    this.DizilerField = value;
                    this.RaisePropertyChanged("Diziler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Filmler[] Filmler {
            get {
                return this.FilmlerField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmlerField, value) != true)) {
                    this.FilmlerField = value;
                    this.RaisePropertyChanged("Filmler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KategoriAdi {
            get {
                return this.KategoriAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KategoriAdiField, value) != true)) {
                    this.KategoriAdiField = value;
                    this.RaisePropertyChanged("KategoriAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KategoriId {
            get {
                return this.KategoriIdField;
            }
            set {
                if ((this.KategoriIdField.Equals(value) != true)) {
                    this.KategoriIdField = value;
                    this.RaisePropertyChanged("KategoriId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yonetmenler", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Yonetmenler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Diziler[] DizilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Filmler[] FilmlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YonetmenAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YonetmenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YonetmenSoyadiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Diziler[] Diziler {
            get {
                return this.DizilerField;
            }
            set {
                if ((object.ReferenceEquals(this.DizilerField, value) != true)) {
                    this.DizilerField = value;
                    this.RaisePropertyChanged("Diziler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Filmler[] Filmler {
            get {
                return this.FilmlerField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmlerField, value) != true)) {
                    this.FilmlerField = value;
                    this.RaisePropertyChanged("Filmler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YonetmenAdi {
            get {
                return this.YonetmenAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.YonetmenAdiField, value) != true)) {
                    this.YonetmenAdiField = value;
                    this.RaisePropertyChanged("YonetmenAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YonetmenId {
            get {
                return this.YonetmenIdField;
            }
            set {
                if ((this.YonetmenIdField.Equals(value) != true)) {
                    this.YonetmenIdField = value;
                    this.RaisePropertyChanged("YonetmenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YonetmenSoyadi {
            get {
                return this.YonetmenSoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.YonetmenSoyadiField, value) != true)) {
                    this.YonetmenSoyadiField = value;
                    this.RaisePropertyChanged("YonetmenSoyadi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiziDetay", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class DiziDetay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BolumIcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> BolumSuresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiziBolumAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiziDetayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiziIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.DiziOyuncular[] DiziOyuncularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiziVideoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Diziler DizilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SezonAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YasSiniriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> YayinlanmaTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BolumIcerik {
            get {
                return this.BolumIcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.BolumIcerikField, value) != true)) {
                    this.BolumIcerikField = value;
                    this.RaisePropertyChanged("BolumIcerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> BolumSuresi {
            get {
                return this.BolumSuresiField;
            }
            set {
                if ((this.BolumSuresiField.Equals(value) != true)) {
                    this.BolumSuresiField = value;
                    this.RaisePropertyChanged("BolumSuresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiziBolumAdi {
            get {
                return this.DiziBolumAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziBolumAdiField, value) != true)) {
                    this.DiziBolumAdiField = value;
                    this.RaisePropertyChanged("DiziBolumAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiziDetayId {
            get {
                return this.DiziDetayIdField;
            }
            set {
                if ((this.DiziDetayIdField.Equals(value) != true)) {
                    this.DiziDetayIdField = value;
                    this.RaisePropertyChanged("DiziDetayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiziId {
            get {
                return this.DiziIdField;
            }
            set {
                if ((this.DiziIdField.Equals(value) != true)) {
                    this.DiziIdField = value;
                    this.RaisePropertyChanged("DiziId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.DiziOyuncular[] DiziOyuncular {
            get {
                return this.DiziOyuncularField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziOyuncularField, value) != true)) {
                    this.DiziOyuncularField = value;
                    this.RaisePropertyChanged("DiziOyuncular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiziVideo {
            get {
                return this.DiziVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziVideoField, value) != true)) {
                    this.DiziVideoField = value;
                    this.RaisePropertyChanged("DiziVideo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Diziler Diziler {
            get {
                return this.DizilerField;
            }
            set {
                if ((object.ReferenceEquals(this.DizilerField, value) != true)) {
                    this.DizilerField = value;
                    this.RaisePropertyChanged("Diziler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SezonAdi {
            get {
                return this.SezonAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SezonAdiField, value) != true)) {
                    this.SezonAdiField = value;
                    this.RaisePropertyChanged("SezonAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YasSiniri {
            get {
                return this.YasSiniriField;
            }
            set {
                if ((this.YasSiniriField.Equals(value) != true)) {
                    this.YasSiniriField = value;
                    this.RaisePropertyChanged("YasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> YayinlanmaTarihi {
            get {
                return this.YayinlanmaTarihiField;
            }
            set {
                if ((this.YayinlanmaTarihiField.Equals(value) != true)) {
                    this.YayinlanmaTarihiField = value;
                    this.RaisePropertyChanged("YayinlanmaTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiziOyuncular", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class DiziOyuncular : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.DiziDetay DiziDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiziDetayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiziOyuncuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OyuncuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Oyuncular OyuncularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.DiziDetay DiziDetay {
            get {
                return this.DiziDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziDetayField, value) != true)) {
                    this.DiziDetayField = value;
                    this.RaisePropertyChanged("DiziDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiziDetayId {
            get {
                return this.DiziDetayIdField;
            }
            set {
                if ((this.DiziDetayIdField.Equals(value) != true)) {
                    this.DiziDetayIdField = value;
                    this.RaisePropertyChanged("DiziDetayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiziOyuncuId {
            get {
                return this.DiziOyuncuIdField;
            }
            set {
                if ((this.DiziOyuncuIdField.Equals(value) != true)) {
                    this.DiziOyuncuIdField = value;
                    this.RaisePropertyChanged("DiziOyuncuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OyuncuId {
            get {
                return this.OyuncuIdField;
            }
            set {
                if ((this.OyuncuIdField.Equals(value) != true)) {
                    this.OyuncuIdField = value;
                    this.RaisePropertyChanged("OyuncuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Oyuncular Oyuncular {
            get {
                return this.OyuncularField;
            }
            set {
                if ((object.ReferenceEquals(this.OyuncularField, value) != true)) {
                    this.OyuncularField = value;
                    this.RaisePropertyChanged("Oyuncular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oyuncular", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Oyuncular : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.DiziOyuncular[] DiziOyuncularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.FilmOyuncular[] FilmOyuncularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OyuncuAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OyuncuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OyuncuOdulleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OyuncuSoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlkesiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.DiziOyuncular[] DiziOyuncular {
            get {
                return this.DiziOyuncularField;
            }
            set {
                if ((object.ReferenceEquals(this.DiziOyuncularField, value) != true)) {
                    this.DiziOyuncularField = value;
                    this.RaisePropertyChanged("DiziOyuncular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.FilmOyuncular[] FilmOyuncular {
            get {
                return this.FilmOyuncularField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmOyuncularField, value) != true)) {
                    this.FilmOyuncularField = value;
                    this.RaisePropertyChanged("FilmOyuncular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OyuncuAdi {
            get {
                return this.OyuncuAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.OyuncuAdiField, value) != true)) {
                    this.OyuncuAdiField = value;
                    this.RaisePropertyChanged("OyuncuAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OyuncuId {
            get {
                return this.OyuncuIdField;
            }
            set {
                if ((this.OyuncuIdField.Equals(value) != true)) {
                    this.OyuncuIdField = value;
                    this.RaisePropertyChanged("OyuncuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OyuncuOdulleri {
            get {
                return this.OyuncuOdulleriField;
            }
            set {
                if ((object.ReferenceEquals(this.OyuncuOdulleriField, value) != true)) {
                    this.OyuncuOdulleriField = value;
                    this.RaisePropertyChanged("OyuncuOdulleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OyuncuSoyadi {
            get {
                return this.OyuncuSoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.OyuncuSoyadiField, value) != true)) {
                    this.OyuncuSoyadiField = value;
                    this.RaisePropertyChanged("OyuncuSoyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulkesi {
            get {
                return this.UlkesiField;
            }
            set {
                if ((object.ReferenceEquals(this.UlkesiField, value) != true)) {
                    this.UlkesiField = value;
                    this.RaisePropertyChanged("Ulkesi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilmOyuncular", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class FilmOyuncular : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmOyuncuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Filmler FilmlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OyuncuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Oyuncular OyuncularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmOyuncuId {
            get {
                return this.FilmOyuncuIdField;
            }
            set {
                if ((this.FilmOyuncuIdField.Equals(value) != true)) {
                    this.FilmOyuncuIdField = value;
                    this.RaisePropertyChanged("FilmOyuncuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Filmler Filmler {
            get {
                return this.FilmlerField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmlerField, value) != true)) {
                    this.FilmlerField = value;
                    this.RaisePropertyChanged("Filmler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OyuncuId {
            get {
                return this.OyuncuIdField;
            }
            set {
                if ((this.OyuncuIdField.Equals(value) != true)) {
                    this.OyuncuIdField = value;
                    this.RaisePropertyChanged("OyuncuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Oyuncular Oyuncular {
            get {
                return this.OyuncularField;
            }
            set {
                if ((object.ReferenceEquals(this.OyuncularField, value) != true)) {
                    this.OyuncularField = value;
                    this.RaisePropertyChanged("Oyuncular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filmler", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Filmler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmOdulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.FilmOyuncular[] FilmOyuncularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmResimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FilmSuresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FragmanSuresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FragmanVideoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KategoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Kategoriler KategorilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KonusuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.KullaniciFilmDetay[] KullaniciFilmDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlkesiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VizyonTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YasSiniriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YonetmenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.BenimServisim.Yonetmenler YonetmenlerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmAdi {
            get {
                return this.FilmAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmAdiField, value) != true)) {
                    this.FilmAdiField = value;
                    this.RaisePropertyChanged("FilmAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmOdul {
            get {
                return this.FilmOdulField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmOdulField, value) != true)) {
                    this.FilmOdulField = value;
                    this.RaisePropertyChanged("FilmOdul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.FilmOyuncular[] FilmOyuncular {
            get {
                return this.FilmOyuncularField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmOyuncularField, value) != true)) {
                    this.FilmOyuncularField = value;
                    this.RaisePropertyChanged("FilmOyuncular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmResim {
            get {
                return this.FilmResimField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmResimField, value) != true)) {
                    this.FilmResimField = value;
                    this.RaisePropertyChanged("FilmResim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FilmSuresi {
            get {
                return this.FilmSuresiField;
            }
            set {
                if ((this.FilmSuresiField.Equals(value) != true)) {
                    this.FilmSuresiField = value;
                    this.RaisePropertyChanged("FilmSuresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FragmanSuresi {
            get {
                return this.FragmanSuresiField;
            }
            set {
                if ((this.FragmanSuresiField.Equals(value) != true)) {
                    this.FragmanSuresiField = value;
                    this.RaisePropertyChanged("FragmanSuresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FragmanVideo {
            get {
                return this.FragmanVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.FragmanVideoField, value) != true)) {
                    this.FragmanVideoField = value;
                    this.RaisePropertyChanged("FragmanVideo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KategoriId {
            get {
                return this.KategoriIdField;
            }
            set {
                if ((this.KategoriIdField.Equals(value) != true)) {
                    this.KategoriIdField = value;
                    this.RaisePropertyChanged("KategoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Kategoriler Kategoriler {
            get {
                return this.KategorilerField;
            }
            set {
                if ((object.ReferenceEquals(this.KategorilerField, value) != true)) {
                    this.KategorilerField = value;
                    this.RaisePropertyChanged("Kategoriler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Konusu {
            get {
                return this.KonusuField;
            }
            set {
                if ((object.ReferenceEquals(this.KonusuField, value) != true)) {
                    this.KonusuField = value;
                    this.RaisePropertyChanged("Konusu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.KullaniciFilmDetay[] KullaniciFilmDetay {
            get {
                return this.KullaniciFilmDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciFilmDetayField, value) != true)) {
                    this.KullaniciFilmDetayField = value;
                    this.RaisePropertyChanged("KullaniciFilmDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulkesi {
            get {
                return this.UlkesiField;
            }
            set {
                if ((object.ReferenceEquals(this.UlkesiField, value) != true)) {
                    this.UlkesiField = value;
                    this.RaisePropertyChanged("Ulkesi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Video {
            get {
                return this.VideoField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoField, value) != true)) {
                    this.VideoField = value;
                    this.RaisePropertyChanged("Video");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VizyonTarihi {
            get {
                return this.VizyonTarihiField;
            }
            set {
                if ((this.VizyonTarihiField.Equals(value) != true)) {
                    this.VizyonTarihiField = value;
                    this.RaisePropertyChanged("VizyonTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YasSiniri {
            get {
                return this.YasSiniriField;
            }
            set {
                if ((this.YasSiniriField.Equals(value) != true)) {
                    this.YasSiniriField = value;
                    this.RaisePropertyChanged("YasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YonetmenId {
            get {
                return this.YonetmenIdField;
            }
            set {
                if ((this.YonetmenIdField.Equals(value) != true)) {
                    this.YonetmenIdField = value;
                    this.RaisePropertyChanged("YonetmenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.BenimServisim.Yonetmenler Yonetmenler {
            get {
                return this.YonetmenlerField;
            }
            set {
                if ((object.ReferenceEquals(this.YonetmenlerField, value) != true)) {
                    this.YonetmenlerField = value;
                    this.RaisePropertyChanged("Yonetmenler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                if ((this.isDeletedField.Equals(value) != true)) {
                    this.isDeletedField = value;
                    this.RaisePropertyChanged("isDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BenimServisim.IKullaniciServisi")]
    public interface IKullaniciServisi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciServisi/KullanicilariGetir", ReplyAction="http://tempuri.org/IKullaniciServisi/KullanicilariGetirResponse")]
        WebApplication1.BenimServisim.Kullanicilar[] KullanicilariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciServisi/KullanicilariGetir", ReplyAction="http://tempuri.org/IKullaniciServisi/KullanicilariGetirResponse")]
        System.Threading.Tasks.Task<WebApplication1.BenimServisim.Kullanicilar[]> KullanicilariGetirAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKullaniciServisiChannel : WebApplication1.BenimServisim.IKullaniciServisi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciServisiClient : System.ServiceModel.ClientBase<WebApplication1.BenimServisim.IKullaniciServisi>, WebApplication1.BenimServisim.IKullaniciServisi {
        
        public KullaniciServisiClient() {
        }
        
        public KullaniciServisiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciServisiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServisiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServisiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.BenimServisim.Kullanicilar[] KullanicilariGetir() {
            return base.Channel.KullanicilariGetir();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.BenimServisim.Kullanicilar[]> KullanicilariGetirAsync() {
            return base.Channel.KullanicilariGetirAsync();
        }
    }
}
